import os
import numpy as np
import open3d as o3d
import argparse

PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
PREDICTION_DIR = os.path.join(PROJECT_DIR, 'predictions')

argparser = argparse.ArgumentParser()
argparser.add_argument('--dataset', type=str, choices=['temple', 'mini-temple'])
args = argparser.parse_args()

DATASET = args.dataset
DATASET_DIR = os.path.join(PREDICTION_DIR, DATASET)

def visualize_point_cloud(dataset):
    """
    Visualizes the 3D point cloud generated by SFM.
    
    Args:
        dataset: Dataset name ('temple' or 'mini-temple')
    """
    # Paths to 3D points
    no_ba_path = os.path.join(DATASET_DIR, 'results', 'no-bundle-adjustment', 'points3d.npy')
    ba_path = os.path.join(DATASET_DIR, 'results', 'bundle-adjustment', 'points3d.npy')
    
    # Check if files exist
    if os.path.exists(no_ba_path):
        print(f"Visualizing point cloud without bundle adjustment for {dataset}...")
        points3d_no_ba = np.load(no_ba_path)
        visualize(points3d_no_ba, "No Bundle Adjustment")
    
    if os.path.exists(ba_path):
        print(f"Visualizing point cloud with bundle adjustment for {dataset}...")
        points3d_ba = np.load(ba_path)
        visualize(points3d_ba, "With Bundle Adjustment")

def visualize(points3d, title):
    """
    Visualizes a 3D point cloud using Open3D.
    
    Args:
        points3d: Numpy array of 3D points (N x 3)
        title: Title for the visualization window
    """
    # Create point cloud
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points3d)
    
    # Add some color for better visualization
    pcd.paint_uniform_color([0.5, 0.5, 0.5])
    
    # Visualize
    print(f"Press 'Q' to close the window for: {title}")
    o3d.visualization.draw_geometries([pcd], window_name=title)

if __name__ == '__main__':
    visualize_point_cloud(DATASET)